// <auto-generated />
using Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250727074909_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Models.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("App.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstNodeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTwoWay")
                        .HasColumnType("boolean");

                    b.Property<int?>("NodeId")
                        .HasColumnType("integer");

                    b.Property<int?>("NodeId1")
                        .HasColumnType("integer");

                    b.Property<int>("SecondeNodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstNodeId");

                    b.HasIndex("NodeId");

                    b.HasIndex("NodeId1");

                    b.HasIndex("SecondeNodeId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("App.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("App.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("App.Models.Floor", b =>
                {
                    b.HasOne("App.Models.Venue", "Venue")
                        .WithMany("Floors")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("App.Models.Line", b =>
                {
                    b.HasOne("App.Models.Node", "FirstNode")
                        .WithMany()
                        .HasForeignKey("FirstNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Models.Node", null)
                        .WithMany("LinesFrom")
                        .HasForeignKey("NodeId");

                    b.HasOne("App.Models.Node", null)
                        .WithMany("LinesTo")
                        .HasForeignKey("NodeId1");

                    b.HasOne("App.Models.Node", "SecondeNode")
                        .WithMany()
                        .HasForeignKey("SecondeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstNode");

                    b.Navigation("SecondeNode");
                });

            modelBuilder.Entity("App.Models.Node", b =>
                {
                    b.HasOne("App.Models.Floor", "Floor")
                        .WithMany("Nodes")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("App.Models.Floor", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("App.Models.Node", b =>
                {
                    b.Navigation("LinesFrom");

                    b.Navigation("LinesTo");
                });

            modelBuilder.Entity("App.Models.Venue", b =>
                {
                    b.Navigation("Floors");
                });
#pragma warning restore 612, 618
        }
    }
}
